// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ20531ROukY5PdF73nPyvggGjOKucjus',
    appId: '1:308624487050:web:5be71089a4c6b7ceadf373',
    messagingSenderId: '308624487050',
    projectId: 'authentication-f1dc2',
    authDomain: 'authentication-f1dc2.firebaseapp.com',
    storageBucket: 'authentication-f1dc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdlyue6ZS5yWlKtN7w-RlHmG2a3xF3IZo',
    appId: '1:308624487050:android:6053121ec337f0d2adf373',
    messagingSenderId: '308624487050',
    projectId: 'authentication-f1dc2',
    storageBucket: 'authentication-f1dc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYxpPpUXMAT7itN2wh1KbLg5O142ErKY',
    appId: '1:308624487050:ios:9de06443189e2411adf373',
    messagingSenderId: '308624487050',
    projectId: 'authentication-f1dc2',
    storageBucket: 'authentication-f1dc2.appspot.com',
    iosClientId: '308624487050-oieg4s7rjpbtp1at15b2v329akhbp803.apps.googleusercontent.com',
    iosBundleId: 'com.example.abbyride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYxpPpUXMAT7itN2wh1KbLg5O142ErKY',
    appId: '1:308624487050:ios:9de06443189e2411adf373',
    messagingSenderId: '308624487050',
    projectId: 'authentication-f1dc2',
    storageBucket: 'authentication-f1dc2.appspot.com',
    iosClientId: '308624487050-oieg4s7rjpbtp1at15b2v329akhbp803.apps.googleusercontent.com',
    iosBundleId: 'com.example.abbyride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ20531ROukY5PdF73nPyvggGjOKucjus',
    appId: '1:308624487050:web:eddb23ca85615643adf373',
    messagingSenderId: '308624487050',
    projectId: 'authentication-f1dc2',
    authDomain: 'authentication-f1dc2.firebaseapp.com',
    storageBucket: 'authentication-f1dc2.appspot.com',
  );

}